export const COLLEGES = [
  {
    id: 1,
    college_name: 'NITK Surathkal',
    location: 'Surathkal',
    college_type: 'Government',
    naac_grade: 'A++',
    top_course: 'BTech Computer Science',
    total_fees: 560000,
    highest_package: 5400000,
    rating: 4.6,
    official_website_url: 'https://www.nitk.ac.in'
  },
  {
    id: 2,
    college_name: 'Sahyadri College of Engineering and Management',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'A',
    top_course: 'BE Computer Science',
    total_fees: 1204400,
    highest_package: 4000000,
    rating: 4.1,
    official_website_url: 'https://sahyadri.edu.in'
  },
  {
    id: 3,
    college_name: 'St Joseph Engineering College',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'A+',
    top_course: 'BE Computer Science',
    total_fees: 976440,
    highest_package: 2750000,
    rating: 4.0,
    official_website_url: 'https://sjec.ac.in'
  },
  {
    id: 4,
    college_name: 'Mangalore Institute of Technology and Engineering',
    location: 'Moodubidire',
    college_type: 'Private',
    naac_grade: 'A+',
    top_course: 'BE Robotics and AI',
    total_fees: 1046000,
    highest_package: 5000000,
    rating: 4.1,
    official_website_url: 'https://mite.ac.in'
  },
  {
    id: 5,
    college_name: 'Canara Engineering College',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'A',
    top_course: 'BE Information Science',
    total_fees: 800000,
    highest_package: 2368000,
    rating: 3.7,
    official_website_url: 'https://canaraengineering.in'
  },
  {
    id: 6,
    college_name: 'SDM Institute of Technology',
    location: 'Ujire',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 764444,
    highest_package: 1200000,
    rating: 3.9,
    official_website_url: null
  },
  {
    id: 7,
    college_name: 'Alva\'s Institute of Engineering and Technology',
    location: 'Moodubidire',
    college_type: 'Private',
    naac_grade: 'A+',
    top_course: 'BE Computer Science',
    total_fees: 880000,
    highest_package: 2000000,
    rating: 4.1,
    official_website_url: 'https://aiet.org.in'
  },
  {
    id: 8,
    college_name: 'AJ Institute of Engineering and Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 449640,
    highest_package: 1400000,
    rating: 3.5,
    official_website_url: 'https://ajiet.edu.in'
  },
  {
    id: 9,
    college_name: 'Srinivas University',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'A',
    top_course: 'BTech AIML',
    total_fees: 874500,
    highest_package: 1700000,
    rating: 3.8,
    official_website_url: 'https://srinivasuniversity.edu.in'
  },
  {
    id: 10,
    college_name: 'Dr MV Shetty Institute of Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE AIML',
    total_fees: 449640,
    highest_package: 1000000,
    rating: 3.8,
    official_website_url: null
  },
  {
    id: 11,
    college_name: 'Yenepoya Institute of Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Information Science',
    total_fees: 544000,
    highest_package: 1000000,
    rating: 4.1,
    official_website_url: 'https://yit.edu.in'
  },
  {
    id: 12,
    college_name: 'PA College of Engineering',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 417360,
    highest_package: 725000,
    rating: 3.8,
    official_website_url: 'https://pace.edu.in'
  },
  {
    id: 13,
    college_name: 'Bearys Institute of Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'B+',
    top_course: 'BE Computer Science',
    total_fees: 800000,
    highest_package: 600000,
    rating: 3.9,
    official_website_url: 'https://bitmangalore.edu.in'
  },
  {
    id: 14,
    college_name: 'Shree Devi Institute of Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 800000,
    highest_package: 506000,
    rating: 3.7,
    official_website_url: 'https://sdc.edu.in'
  },
  {
    id: 15,
    college_name: 'Karavali Institute of Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Artificial Intelligence',
    total_fees: 417060,
    highest_package: 300000,
    rating: 3.7,
    official_website_url: 'http://karavaliengineering.ac.in'
  },
  {
    id: 16,
    college_name: 'Yenepoya University',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'A+',
    top_course: 'BTech AIML',
    total_fees: 926000,
    highest_package: 900000,
    rating: 3.9,
    official_website_url: 'https://yenepoya.edu.in'
  },
  {
    id: 17,
    college_name: 'Nitte Meenakshi Institute of Technology',
    location: 'Nitte',
    college_type: 'Private',
    naac_grade: 'A+',
    top_course: 'BTech Computer Science',
    total_fees: 1440000,
    highest_package: 5893000,
    rating: 4.0,
    official_website_url: 'https://nmit.ac.in'
  },
  {
    id: 18,
    college_name: 'NMAM Institute of Technology',
    location: 'Nitte',
    college_type: 'Private',
    naac_grade: 'A+',
    top_course: 'BTech Computer Science',
    total_fees: 1280000,
    highest_package: 5200000,
    rating: 4.3,
    official_website_url: 'https://nmamit.nitte.edu.in'
  },
  {
    id: 19,
    college_name: 'Srinivas Institute of Technology',
    location: 'Valachil',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 500000,
    highest_package: 700000,
    rating: 3.6,
    official_website_url: 'https://sitmng.ac.in'
  },
  {
    id: 20,
    college_name: 'Mangalore Marine College and Technology',
    location: 'Kuppepadavu',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'Marine Engineering',
    total_fees: 600000,
    highest_package: 900000,
    rating: 3.5,
    official_website_url: 'http://mmct.edu.in'
  },
  {
    id: 21,
    college_name: 'Vivekananda College of Engineering and Technology',
    location: 'Puttur',
    college_type: 'Private',
    naac_grade: 'A',
    top_course: 'BE Computer Science',
    total_fees: 700000,
    highest_package: 1200000,
    rating: 4.0,
    official_website_url: 'https://vcetputtur.ac.in'
  },
  {
    id: 22,
    college_name: 'KVG College of Engineering',
    location: 'Sullia',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 600000,
    highest_package: 800000,
    rating: 3.6,
    official_website_url: 'https://kvgengg.com'
  },
  {
    id: 23,
    college_name: 'Shree Devi Education Trust Engineering College',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Information Science',
    total_fees: 650000,
    highest_package: 500000,
    rating: 3.5,
    official_website_url: 'https://sdc.edu.in'
  },
  {
    id: 24,
    college_name: 'Canara Group of Institutions',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 700000,
    highest_package: 600000,
    rating: 3.5,
    official_website_url: 'https://canaracollege.com'
  },
  {
    id: 25,
    college_name: 'Quad AI School of Management and Technology',
    location: 'Mangalore',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BTech AIML',
    total_fees: 950000,
    highest_package: 1000000,
    rating: 3.8,
    official_website_url: 'https://quad.ai'
  },
  {
    id: 26,
    college_name: 'Srinivas School of Engineering',
    location: 'Mukka',
    college_type: 'Private',
    naac_grade: 'NA',
    top_course: 'BE Computer Science',
    total_fees: 550000,
    highest_package: 700000,
    rating: 3.6,
    official_website_url: 'https://srinivasgroup.com'
  }
]
